
params:
  # add search params, refer to https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    includeMatches: true
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
