baseURL: 'https://bobliu.cc/'
languageCode: 'en-us'
title: 'Bob L Blogs'
theme: 'PaperMod'

params:
  profileMode:
    enabled: true
    title: "Bob L" # optional default will be site title
    subtitle: "diving..."
    imageUrl: "https://s2.loli.net/2025/04/21/Bd2qcSlTQUYfDRa.png" # optional
    imageTitle: "Bob_L" # optional
    imageWidth: 100 # custom size
    imageHeight: 100 # custom size
    buttons:
      - name: Archive
        url: "/archives"
      - name: Tags
        url: "/tags"
      - name: Github
        url: "https://github.com/Whaleer/"
      
  defaultTheme: auto # 自动跟随系统


  socialIcons: # optional
    - name: "Github"
      url: "https://github.com/Whaleer/"
    - name: "bilibili"
      url: "https://space.bilibili.com/11530473"
    - name: "QQ"
      url: "https://qm.qq.com/q/aV0GnjPzQA"



  assets:
    # disableHLJS: true
    favicon: "/Users/bingxil/Bob_L_Hugo/static/favicon.ico"
    favicon16x16: "/Users/bingxil/Bob_L_Hugo/static/favicon-16x16.png"
    favicon32x32: "/Users/bingxil/Bob_L_Hugo/static/favicon-32x32.png"
    apple_touch_icon: "/Users/bingxil/Bob_L_Hugo/static/apple-touch-icon.png"
    # safari_pinned_tab: "/Users/bingxil/Bob_L_Hugo/static/safari-pinned-tab.svg"


  ShowAllPagesInArchive: true
  
  # DateFormat: "2006-01-02" # 值是 Golang 中的时间格式化字符串，它的意义是固定的
  ShowFullTextinRSS: true
  
  ShowShareButtons: false
  # show Table of Contents (Toc) on blog post
  ShowToc: true
  ShowBreadCrumbs: true

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: true
  enableEmoji: true

taxonomies:
    category: categories
    tag: tags



# automatically menu
# sectionPagesMenu: main

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10

    - identifier: tags
      name: Tags
      url: tags/
      weight: 20

    - identifier: Archive
      name: Archive
      url: /archives/
      weight: 30

    - identifier: search
      name: Search
      url: /search/
      weight: 40

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1   #行从几开始
    lineNos: true   #是否显示行列
    lineNumbersInTable: true
    noClasses: false
    style: catppuccin-frappe   #代码样式


